language = "C"
cpp_compat = true

include_guard = "libenturion_authserver_h"

[defines]
"windows" = "_WIN32"

[enum]
rename_variants = "ScreamingSnakeCase"

[parse.expand]
crates = ["enturion_authserver"]
