REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'kitron'@'localhost';

DROP USER 'kitron'@'localhost';

DROP DATABASE IF EXISTS `world`;

DROP DATABASE IF EXISTS `characters`;

DROP DATABASE IF EXISTS `auth`;
