[package]
name = "libenturion"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "lib.rs"

[dependencies]
enturion_shared = { path = "shared" }

[workspace]
resolver = "2"
members = [
    "shared",
    "authserver",
]
