language = "C"
header = "#define FFI_CONFIG 1\n#define FFI_LOG 1"
cpp_compat = true
include_guard = "libenturion_shared_h"

[defines]
"windows" = "_WIN32"
"feature = ffi_config" = "FFI_CONFIG"
"feature = ffi_log" = "FFI_LOG"

[enum]
rename_variants = "ScreamingSnakeCase"

[export]
include = ["DbcFieldFormat"]
